#! /bin/bash

echo "Compiling..."
args="-Wall -Waddress -Wextra"
version="-std=c++20"
name="learn"
if [ ! -d "./build" ]; then
	mkdir "./build"
fi
clang++ $args "$version" "$name.cpp" -o "./build/$name"

echo
echo "Building..."
"./build/$name"
